import { Check } from 'lucide-react';
import type { LensSelection } from '../../types';

export const lensMaterials = [{ name: 'Standard Lens', description: 'Clear everyday vision', material: 'Standard', price: 0 }, { name: 'Thin Lens', description: 'Lighter profile for higher powers', material: 'Thin', price: 35 }, { name: 'Ultra Thin Lens', description: 'Our slimmest premium finish', material: 'Ultra Thin', price: 70 }];
export const lensCoatings = [{ name: 'Anti-Reflective', price: 15 }, { name: 'Blue Light Protection', price: 20 }, { name: 'Scratch Resistant', price: 10 }, { name: 'UV Protection', price: 10 }];

type LensSelectorProps = { value: LensSelection; onChange: (value: LensSelection) => void };
export default function LensSelector({ value, onChange }: LensSelectorProps) {
  const toggleCoating = (coating: string, price: number) => { const selected = value.coatings.includes(coating); onChange({ ...value, coatings: selected ? value.coatings.filter((item) => item !== coating) : [...value.coatings, coating], additionalPrice: value.additionalPrice + (selected ? -price : price) }); };
  const chooseMaterial = (material: typeof lensMaterials[number]) => { const coatingTotal = lensCoatings.filter((coating) => value.coatings.includes(coating.name)).reduce((sum, coating) => sum + coating.price, 0); onChange({ ...value, type: material.name, material: material.material, additionalPrice: material.price + coatingTotal }); };
  return <div className="space-y-6"><section><h2 className="text-lg font-semibold text-white">Lens material</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{lensMaterials.map((lens) => <button key={lens.material} onClick={() => chooseMaterial(lens)} className={`rounded-2xl border p-4 text-left ${value.material === lens.material ? 'border-cyan-400/60 bg-cyan-400/10' : 'border-white/10 bg-[#151823]'}`}><span className="flex items-center justify-between font-semibold text-white">{lens.name}{value.material === lens.material ? <Check className="h-4 w-4 text-cyan-300" /> : null}</span><span className="mt-2 block text-sm text-slate-400">{lens.description}</span><span className="mt-3 block text-sm text-cyan-300">{lens.price ? `+$${lens.price}` : 'Included'}</span></button>)}</div></section><section><h2 className="text-lg font-semibold text-white">Lens coatings</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{lensCoatings.map((coating) => <button key={coating.name} onClick={() => toggleCoating(coating.name, coating.price)} className={`flex items-center justify-between rounded-2xl border p-4 text-left ${value.coatings.includes(coating.name) ? 'border-cyan-400/60 bg-cyan-400/10' : 'border-white/10 bg-[#151823]'}`}><span className="text-sm font-semibold text-white">{coating.name}</span><span className="flex items-center gap-3 text-sm text-cyan-300">+${coating.price}{value.coatings.includes(coating.name) ? <Check className="h-4 w-4" /> : null}</span></button>)}</div></section></div>;
}
