import type { ChangeEvent } from 'react';
import type { Prescription } from '../../types';

type PrescriptionFormProps = { value: Prescription; errors: Record<string, string>; onChange: (value: Prescription) => void };
const fields = [['sph', 'SPH', 'Sphere'], ['cyl', 'CYL', 'Cylinder'], ['axis', 'AXIS', 'Axis'], ['add', 'ADD', 'Addition']] as const;

export default function PrescriptionForm({ value, errors, onChange }: PrescriptionFormProps) {
  const updateEye = (eye: 'rightEye' | 'leftEye', field: 'sph' | 'cyl' | 'axis' | 'add', next: string) => onChange({ ...value, [eye]: { ...value[eye], [field]: next } });
  const eyeInput = (eye: 'rightEye' | 'leftEye', field: 'sph' | 'cyl' | 'axis' | 'add', label: string, hint: string) => <label className="space-y-2 text-sm text-slate-300"><span className="flex justify-between gap-2"><span>{label}</span><span className="text-xs text-slate-500">{hint}</span></span><input value={value[eye][field]} onChange={(event) => updateEye(eye, field, event.target.value)} inputMode="decimal" placeholder="Not entered" className="w-full rounded-xl border border-white/10 bg-[#151823] px-3 py-3 text-white outline-none transition focus:border-cyan-400" />{errors[`${eye}.${field}`] ? <span className="block text-xs text-red-300">{errors[`${eye}.${field}`]}</span> : null}</label>;
  return <div className="space-y-6"><div className="grid gap-5 lg:grid-cols-2">{(['rightEye', 'leftEye'] as const).map((eye) => <section key={eye} className="rounded-[20px] border border-white/10 bg-[#1B1F2B] p-5"><h3 className="font-semibold text-white">{eye === 'rightEye' ? 'RIGHT EYE (OD)' : 'LEFT EYE (OS)'}</h3><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map(([field, label, hint]) => eyeInput(eye, field, label, hint))}</div></section>)}</div><section className="rounded-[20px] border border-white/10 bg-[#151823] p-5"><h3 className="font-semibold text-white">Pupillary distance (PD)</h3><p className="mt-1 text-xs text-slate-500">Distance between your pupils, measured in millimetres.</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="space-y-2 text-sm text-slate-300"><span>Total PD</span><input value={value.pd} onChange={(event: ChangeEvent<HTMLInputElement>) => onChange({ ...value, pd: event.target.value })} inputMode="decimal" placeholder="e.g. 62" className="w-full rounded-xl border border-white/10 bg-[#1B1F2B] px-3 py-3 text-white outline-none focus:border-cyan-400" />{errors.pd ? <span className="block text-xs text-red-300">{errors.pd}</span> : null}</label><label className="space-y-2 text-sm text-slate-300"><span>Right PD (optional)</span><input value={value.rightPd ?? ''} onChange={(event) => onChange({ ...value, rightPd: event.target.value })} inputMode="decimal" className="w-full rounded-xl border border-white/10 bg-[#1B1F2B] px-3 py-3 text-white outline-none focus:border-cyan-400" /></label><label className="space-y-2 text-sm text-slate-300"><span>Left PD (optional)</span><input value={value.leftPd ?? ''} onChange={(event) => onChange({ ...value, leftPd: event.target.value })} inputMode="decimal" className="w-full rounded-xl border border-white/10 bg-[#1B1F2B] px-3 py-3 text-white outline-none focus:border-cyan-400" /></label></div></section><p className="text-xs text-slate-500">This is a UI representation only. Dream Spex does not diagnose or prescribe lenses.</p></div>;
}
