import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Apple, ArrowRight, Mail } from 'lucide-react';
import AuthLayout from '../components/auth/AuthLayout';
import OtpVerification from '../components/auth/OtpVerification';
import PasswordField from '../components/auth/PasswordField';
import { authService } from '../services/authService';
import { useAuth } from '../context/useAuth';

type Mode = 'login' | 'register' | 'forgot'; type Errors = Record<string, string>;
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; const phonePattern = /^\+?[0-9\s()-]{8,18}$/; const validIdentifier = (value: string) => emailPattern.test(value) || phonePattern.test(value);
const Field = ({ id, label, value, onChange, error, type = 'text', autoComplete, placeholder, icon }: { id: string; label: string; value: string; onChange: (value: string) => void; error?: string; type?: string; autoComplete?: string; placeholder?: string; icon?: React.ReactNode }) => <div className="auth-field-wrap"><label htmlFor={id}>{label}</label><div className="auth-input-wrap">{icon ? <span className="auth-input-icon" aria-hidden="true">{icon}</span> : null}<input id={id} type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} autoComplete={autoComplete} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} /></div>{error ? <span id={`${id}-error`} className="auth-error">{error}</span> : null}</div>;

export default function AuthPage({ mode }: { mode: Mode }) {
  const navigate = useNavigate(); const { setAuthenticated } = useAuth(); const [step, setStep] = useState<'form' | 'otp' | 'reset' | 'success'>('form'); const [loading, setLoading] = useState(false); const [errors, setErrors] = useState<Errors>({}); const [form, setForm] = useState({ identifier: '', name: '', email: '', phone: '', password: '', confirmPassword: '' }); const setValue = (key: keyof typeof form) => (value: string) => setForm((current) => ({ ...current, [key]: value })); const identifier = mode === 'forgot' ? form.identifier : form.email; const maskedIdentifier = identifier.includes('@') ? `${identifier[0]}****${identifier.slice(identifier.indexOf('@'))}` : `******${identifier.replace(/\D/g, '').slice(-4)}`;
  useEffect(() => { setStep('form'); setLoading(false); setErrors({}); setForm({ identifier: '', name: '', email: '', phone: '', password: '', confirmPassword: '' }); }, [mode]);
  const validate = () => { const next: Errors = {}; if (mode === 'login' || mode === 'forgot') { if (!form.identifier.trim()) next.identifier = 'Email or phone number is required.'; else if (!validIdentifier(form.identifier.trim())) next.identifier = 'Enter a valid email or phone number.'; } if (mode === 'register') { if (form.name.trim().length < 2) next.name = 'Please enter your full name.'; if (!emailPattern.test(form.email)) next.email = 'Enter a valid email address.'; if (!phonePattern.test(form.phone)) next.phone = 'Enter a valid phone number.'; } if (mode === 'login' && form.password.length < 8) next.password = 'Use at least 8 characters.'; if (mode === 'register' && form.password.length < 8) next.password = 'Use at least 8 characters.'; if (mode === 'register' && form.confirmPassword !== form.password) next.confirmPassword = 'Passwords do not match.'; setErrors(next); return Object.keys(next).length === 0; };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!validate()) return; setLoading(true); try { if (mode === 'login') { await authService.login({ identifier: form.identifier, password: form.password }); setAuthenticated(); navigate('/', { replace: true }); } else if (mode === 'register') { await authService.register({ name: form.name, email: form.email, phone: form.phone, password: form.password }); setStep('otp'); } else { await authService.resendOtp(form.identifier); setStep('otp'); } } finally { setLoading(false); } };
  if (step === 'otp') return <AuthLayout><OtpVerification identifier={maskedIdentifier} onBack={() => setStep('form')} onVerified={async (otp) => { await authService.verifyOtp(identifier, otp); setStep(mode === 'forgot' ? 'reset' : 'success'); }} onResend={async () => { await authService.resendOtp(identifier); }} /></AuthLayout>;
  if (step === 'reset') return <AuthLayout><div className="auth-content auth-animate"><span className="auth-step">STEP 03 / SECURE</span><h1>Choose a new password</h1><p className="auth-description">Create a new password for your Dream Spex account.</p><form onSubmit={async (event) => { event.preventDefault(); const next: Errors = {}; if (form.password.length < 8) next.password = 'Use at least 8 characters.'; if (form.confirmPassword !== form.password) next.confirmPassword = 'Passwords do not match.'; setErrors(next); if (Object.keys(next).length) return; setLoading(true); await authService.resetPassword(identifier, form.password); setLoading(false); setStep('success'); }}><PasswordField id="password" label="New password" value={form.password} onChange={setValue('password')} error={errors.password} autoComplete="new-password" /><PasswordField id="confirmPassword" label="Confirm new password" value={form.confirmPassword} onChange={setValue('confirmPassword')} error={errors.confirmPassword} autoComplete="new-password" /><button className="auth-primary" type="submit" disabled={loading}>{loading ? <><span className="auth-spinner" /> Updating...</> : 'Update password'}</button></form></div></AuthLayout>;
  if (step === 'success') return <AuthLayout><div className="auth-content auth-success auth-animate"><span className="success-mark">✓</span><span className="auth-step">DREAM SPEX / COMPLETE</span><h1>{mode === 'login' ? 'Welcome back.' : mode === 'forgot' ? 'Password updated successfully' : 'Account created successfully'}</h1><p className="auth-description">{mode === 'login' ? 'Your private eyewear edit is ready.' : mode === 'forgot' ? 'Your password has been reset.' : 'Welcome to Dream Spex.'}</p><button className="auth-primary" onClick={() => navigate('/login', { replace: true })}>{mode === 'login' ? 'Continue shopping' : mode === 'forgot' ? 'Back to login' : 'Continue to login'} <ArrowRight size={17} /></button></div></AuthLayout>;
  const title = mode === 'login' ? 'Welcome back.' : mode === 'register' ? 'Create your account.' : 'Reset your password.'; const description = mode === 'login' ? 'Your private eyewear edit is ready.' : mode === 'register' ? 'Join Dream Spex and make every view your own.' : 'Enter your details and we\'ll help you get back in.';
  return <AuthLayout><div className="auth-content auth-animate"><span className="auth-step">{mode === 'register' ? 'STEP 01 / JOIN' : mode === 'forgot' ? 'DREAM SPEX / ACCOUNT RECOVERY' : 'DREAM SPEX / PRIVATE ACCESS'}</span><h1>{title}</h1><p className="auth-description">{description}</p><form onSubmit={submit} noValidate>{mode === 'register' ? <><Field id="name" label="Full name" value={form.name} onChange={setValue('name')} error={errors.name} autoComplete="name" placeholder="Enter your full name" /><Field id="email" label="Email address" value={form.email} onChange={setValue('email')} error={errors.email} type="email" autoComplete="email" placeholder="Enter your email address" /><Field id="phone" label="Phone number" value={form.phone} onChange={setValue('phone')} error={errors.phone} type="tel" autoComplete="tel" placeholder="Enter your phone number" /></> : <Field id="identifier" label="Email or phone number" value={form.identifier} onChange={setValue('identifier')} error={errors.identifier} autoComplete="username" placeholder="Enter email or phone number" icon={<Mail size={16} />} />}{mode === 'login' ? <><PasswordField id="password" label="Password" value={form.password} onChange={setValue('password')} error={errors.password} autoComplete="current-password" /><div className="auth-login-options"><label className="auth-remember"><input type="checkbox" /> <span>Remember me</span></label><Link className="auth-text-link" to="/forgot-password">Forgot password?</Link></div></> : null}{mode === 'register' ? <><PasswordField id="password" label="Password" value={form.password} onChange={setValue('password')} error={errors.password} autoComplete="new-password" /><PasswordField id="confirmPassword" label="Confirm password" value={form.confirmPassword} onChange={setValue('confirmPassword')} error={errors.confirmPassword} autoComplete="new-password" /></> : null}<button className="auth-primary" type="submit" disabled={loading}>{loading ? <><span className="auth-spinner" /> {mode === 'login' ? 'Signing in...' : mode === 'forgot' ? 'Sending code...' : 'Creating account...'}</> : mode === 'login' ? <>Sign in <ArrowRight size={17} /></> : mode === 'forgot' ? 'Send verification code' : 'Create account'}</button></form>{mode === 'login' ? <><div className="auth-divider"><span>or continue with</span></div><div className="auth-socials"><button type="button" aria-label="Continue with Google" className="auth-social google">G</button><button type="button" aria-label="Continue with Facebook" className="auth-social">f</button><button type="button" aria-label="Continue with Apple" className="auth-social"><Apple size={18} /></button></div></> : null}<p className="auth-switch">{mode === 'register' ? 'Already have an account?' : 'Don&apos;t have an account?'} <Link to={mode === 'register' ? '/login' : '/register'}>{mode === 'register' ? 'Sign in' : 'Create account'}</Link></p></div></AuthLayout>;
}