import { useRef, useState } from 'react';
import { CheckCircle, Camera, CircleAlert, CreditCard, ExternalLink, PackageCheck, Upload, Video, Wrench } from 'lucide-react';
import { Link } from 'react-router-dom';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';
import Button from '../components/ui/Button';
import SectionTitle from '../components/ui/SectionTitle';
import WhatsAppSupport from '../components/ui/WhatsAppSupport';
import { products } from '../data/mockData';
import { useShop } from '../context/ShopContext';

function FlowShell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-[#050816] text-slate-100"><Navbar /><main className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">{children}</main><Footer /></div>;
}

export function VirtualTryOnPage() {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [cameraState, setCameraState] = useState<'idle' | 'loading' | 'ready' | 'denied'>('idle');
  const [selectedFrame, setSelectedFrame] = useState(0);
  const requestCamera = async () => {
    setCameraState('loading');
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user' }, audio: false });
      if (videoRef.current) videoRef.current.srcObject = stream;
      setCameraState('ready');
    } catch { setCameraState('denied'); }
  };
  return <FlowShell><SectionTitle eyebrow="Virtual try-on" title="Find the frame that feels like you" description="Use your camera or upload a photo. This preview is ready for a future face-detection SDK integration." /><div className="mt-10 grid gap-8 lg:grid-cols-[1.3fr_0.7fr]"><div className="relative aspect-video overflow-hidden rounded-[28px] border border-white/10 bg-[#0a1022]"><video ref={videoRef} autoPlay playsInline className={`h-full w-full object-cover ${cameraState === 'ready' ? 'block' : 'hidden'}`} /><div className={`${cameraState === 'ready' ? 'hidden' : 'flex'} h-full flex-col items-center justify-center gap-4 p-8 text-center`}><Video className="h-10 w-10 text-cyan-300" />{cameraState === 'denied' ? <><p className="text-lg font-semibold text-white">Camera access is unavailable</p><p className="max-w-md text-sm text-slate-400">Allow camera access or upload a photo to continue.</p></> : <p className="text-lg font-semibold text-white">Your try-on studio is ready</p>}</div>{cameraState === 'ready' ? <div className="pointer-events-none absolute left-1/2 top-1/2 h-24 w-56 -translate-x-1/2 -translate-y-1/2 rounded-[45%] border-2 border-cyan-300/70 shadow-[0_0_40px_rgba(34,211,238,0.35)]" /> : null}</div><aside className="rounded-[28px] border border-white/10 bg-white/5 p-6"><p className="text-sm uppercase tracking-[0.3em] text-cyan-400">Choose a frame</p><div className="mt-5 space-y-3">{products.map((product, index) => <button key={product.id} onClick={() => setSelectedFrame(index)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left ${selectedFrame === index ? 'border-cyan-400/50 bg-cyan-400/10' : 'border-white/10 bg-slate-950/50'}`}><img src={product.image} alt="" className="h-12 w-12 rounded-xl object-cover" /><span className="text-sm font-semibold text-white">{product.name}</span></button>)}</div><div className="mt-6 grid gap-3"><Button onClick={requestCamera} fullWidth><Camera className="mr-2 h-4 w-4" />{cameraState === 'loading' ? 'Requesting camera...' : 'Start try-on'}</Button><label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-full border border-white/10 bg-white/5 px-5 py-3 text-sm font-semibold text-slate-200"><Upload className="h-4 w-4" /> Upload photo<input type="file" accept="image/*" className="sr-only" /></label><Link to={`/product/${products[selectedFrame].id}`} className="inline-flex items-center justify-center gap-2 text-sm font-semibold text-cyan-300">View selected frame <ExternalLink className="h-4 w-4" /></Link></div></aside></div></FlowShell>;
}

export function PaymentPage() {
  const { cart, total } = useShop();
  const [method, setMethod] = useState('card');
  const [notice, setNotice] = useState(false);
  return <FlowShell><SectionTitle eyebrow="Payment" title="Choose how you would like to pay" description="Payment credentials are collected by your gateway, never by this storefront." /><div className="mx-auto mt-10 grid max-w-5xl gap-8 lg:grid-cols-[1fr_0.7fr]"><div className="rounded-[28px] border border-white/10 bg-white/5 p-8"><div className="grid gap-3 sm:grid-cols-2">{[['card', 'Credit or debit card', CreditCard], ['upi', 'UPI', CreditCard], ['netbanking', 'Net banking', PackageCheck], ['cod', 'Cash on delivery', PackageCheck]].map(([value, label, Icon]) => <button key={String(value)} onClick={() => setMethod(String(value))} className={`flex items-center gap-3 rounded-2xl border p-4 text-left ${method === value ? 'border-cyan-400/50 bg-cyan-400/10' : 'border-white/10 bg-slate-950/50'}`}><Icon className="h-5 w-5 text-cyan-300" /><span className="text-sm font-semibold text-white">{String(label)}</span></button>)}</div>{method === 'card' ? <div className="mt-8 grid gap-4"><input placeholder="Cardholder name" className="rounded-full border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none" /><input placeholder="Card number" inputMode="numeric" className="rounded-full border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none" /><div className="grid gap-4 sm:grid-cols-2"><input placeholder="MM / YY" className="rounded-full border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none" /><input placeholder="CVC" className="rounded-full border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none" /></div></div> : <div className="mt-8 rounded-2xl border border-cyan-400/20 bg-cyan-400/10 p-4 text-sm text-slate-300">Your secure payment provider will open after order creation.</div>}<Button fullWidth className="mt-8" onClick={() => setNotice(true)}>Continue to secure payment</Button>{notice ? <div className="mt-4 flex gap-3 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-sm text-amber-100"><CircleAlert className="h-5 w-5 shrink-0" />Gateway integration is not configured yet. No payment or order was created.</div> : null}</div><div className="rounded-[28px] border border-cyan-400/20 bg-gradient-to-br from-[#0f1b37] to-[#060b17] p-8"><p className="text-sm uppercase tracking-[0.3em] text-cyan-300">Order total</p><p className="mt-4 text-4xl font-semibold text-white">${total}</p><p className="mt-3 text-sm text-slate-400">{cart.length} line item{cart.length === 1 ? '' : 's'} · Taxes and delivery calculated at confirmation.</p><Link to="/cart" className="mt-8 inline-flex text-sm font-semibold text-cyan-300">Review cart</Link></div></div></FlowShell>;
}

export function PrescriptionPage() {
  const [step, setStep] = useState(1);
  const [lensType, setLensType] = useState('Single vision');
  const product = products[0];
  return <FlowShell><SectionTitle eyebrow="Prescription lenses" title={`Personalise ${product.name}`} description="Choose your lens and prescription details before adding this frame to your cart." /><div className="mx-auto mt-10 max-w-3xl rounded-[28px] border border-white/10 bg-white/5 p-8"><div className="flex items-center justify-between text-xs uppercase tracking-[0.25em] text-slate-500">{['Lens type', 'Prescription', 'Material', 'Review'].map((label, index) => <span key={label} className={step === index + 1 ? 'text-cyan-300' : ''}>{index + 1}. {label}</span>)}</div><div className="mt-8">{step === 1 ? <div className="grid gap-3 sm:grid-cols-2">{['Single vision', 'Bifocal', 'Progressive', 'Blue light', 'Zero power'].map((option) => <button key={option} onClick={() => setLensType(option)} className={`rounded-2xl border p-4 text-left text-sm font-semibold ${lensType === option ? 'border-cyan-400/50 bg-cyan-400/10 text-white' : 'border-white/10 bg-slate-950/50 text-slate-300'}`}>{option}</button>)}</div> : null}{step === 2 ? <div className="grid gap-4 sm:grid-cols-2">{['Right eye SPH', 'Right eye CYL', 'Right eye AXIS', 'Left eye SPH', 'Left eye CYL', 'Left eye AXIS', 'PD'].map((label) => <input key={label} required placeholder={label} className="rounded-full border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none" />)}<label className="flex cursor-pointer items-center gap-2 rounded-full border border-dashed border-white/10 px-4 py-3 text-sm text-slate-300"><Upload className="h-4 w-4 text-cyan-300" /> Upload prescription<input type="file" accept="image/*,.pdf" className="sr-only" /></label></div> : null}{step === 3 ? <div className="grid gap-3 sm:grid-cols-3">{['Standard', 'Thin', 'Ultra thin'].map((option) => <button key={option} onClick={() => setStep(4)} className="rounded-2xl border border-white/10 bg-slate-950/50 p-5 text-sm font-semibold text-white">{option}</button>)}</div> : null}{step === 4 ? <div className="rounded-2xl border border-cyan-400/20 bg-cyan-400/10 p-5"><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">Review</p><p className="mt-4 font-semibold text-white">{product.name} · {lensType}</p><p className="mt-2 text-sm text-slate-300">Prescription details and anti-reflective coating will be confirmed before payment.</p><Link to="/cart" className="mt-6 inline-flex rounded-full bg-gradient-to-r from-cyan-400 to-blue-600 px-5 py-3 text-sm font-semibold text-white">Continue to cart</Link></div> : null}</div>{step < 4 && step !== 3 ? <Button fullWidth className="mt-8" onClick={() => setStep(step + 1)}>Continue</Button> : null}</div></FlowShell>;
}

export function OrderConfirmationPage() {
  return <FlowShell><div className="mx-auto max-w-3xl rounded-[32px] border border-emerald-400/20 bg-emerald-400/10 p-10 text-center"><CheckCircle className="mx-auto h-14 w-14 text-emerald-300" /><p className="mt-6 text-sm uppercase tracking-[0.3em] text-emerald-300">Order confirmation</p><h1 className="mt-3 text-4xl font-semibold text-white">Your order is on its way</h1><p className="mt-4 text-slate-300">Order confirmation and payment status will appear here after the payment gateway confirms the transaction.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/order-tracking" className="rounded-full bg-gradient-to-r from-cyan-400 to-blue-600 px-5 py-3 text-sm font-semibold text-white">Track order</Link><WhatsAppSupport message="Hello, I need help with my recent Dream Spex order." /></div></div></FlowShell>;
}

export function OrderTrackingPage() {
  const statuses = ['Order placed', 'Payment confirmed', 'Processing', 'Lens preparation', 'Packed', 'Shipped', 'Out for delivery', 'Delivered'];
  return <FlowShell><SectionTitle eyebrow="Orders" title="Track your order" description="Stay close to every step from atelier to doorstep." /><div className="mx-auto mt-10 max-w-3xl rounded-[28px] border border-white/10 bg-white/5 p-8"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-6"><div><p className="text-sm text-slate-400">Order number</p><p className="mt-1 font-semibold text-white">DS-2026-1048</p></div><div><p className="text-sm text-slate-400">Estimated delivery</p><p className="mt-1 font-semibold text-cyan-300">Awaiting confirmation</p></div></div><div className="mt-8 space-y-5">{statuses.map((status, index) => <div key={status} className="flex items-center gap-4"><span className={`flex h-8 w-8 items-center justify-center rounded-full border text-xs ${index === 0 ? 'border-cyan-300 bg-cyan-300 text-slate-950' : 'border-white/10 text-slate-500'}`}>{index + 1}</span><span className={index === 0 ? 'font-semibold text-white' : 'text-slate-500'}>{status}</span></div>)}</div><div className="mt-8 flex flex-wrap gap-3"><WhatsAppSupport message="Hello, I need help with Order DS-2026-1048." /><Link to="/after-sales" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-3 text-sm font-semibold text-slate-200"><Wrench className="h-4 w-4" /> After-sales support</Link></div></div></FlowShell>;
}

export function AfterSalesPage() {
  const [submitted, setSubmitted] = useState(false);
  return <FlowShell><SectionTitle eyebrow="After-sales" title="We keep caring after delivery" description="Start a return, repair, replacement, warranty, or order issue request." />{submitted ? <div className="mx-auto mt-10 max-w-2xl rounded-[28px] border border-emerald-400/20 bg-emerald-400/10 p-10 text-center"><CheckCircle className="mx-auto h-12 w-12 text-emerald-300" /><h2 className="mt-5 text-2xl font-semibold text-white">Request submitted</h2><p className="mt-3 text-sm text-slate-300">Reference DS-SR-1048. Our support team will review it shortly.</p><Link to="/orders" className="mt-6 inline-flex text-sm font-semibold text-cyan-300">View my orders</Link></div> : <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }} className="mx-auto mt-10 max-w-2xl space-y-5 rounded-[28px] border border-white/10 bg-white/5 p-8"><div className="grid gap-5 sm:grid-cols-2"><input required placeholder="Order number" className="rounded-full border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none" /><select className="rounded-full border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none"><option>Return product</option><option>Replacement</option><option>Warranty claim</option><option>Repair request</option><option>Lens issue</option></select></div><textarea required rows={5} placeholder="Tell us what happened" className="w-full rounded-[20px] border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none" /><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-white/10 p-4 text-sm text-slate-300"><Upload className="h-5 w-5 text-cyan-300" /> Add an image<input type="file" accept="image/*" className="sr-only" /></label><Button type="submit" fullWidth>Submit service request</Button></form>}</FlowShell>;
}
