import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, RefreshCw } from 'lucide-react';

export default function OtpVerification({ identifier, onBack, onVerified, onResend }: { identifier: string; onBack: () => void; onVerified: (otp: string) => Promise<void>; onResend: () => Promise<void> }) {
  const [digits, setDigits] = useState(['', '', '', '', '', '']); const [seconds, setSeconds] = useState(30); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [resendLoading, setResendLoading] = useState(false); const inputs = useRef<Array<HTMLInputElement | null>>([]);
  useEffect(() => { if (seconds > 0) { const timer = window.setTimeout(() => setSeconds(seconds - 1), 1000); return () => window.clearTimeout(timer); } }, [seconds]);
  const updateDigit = (index: number, value: string) => { const next = [...digits]; next[index] = value.slice(-1).replace(/\D/g, ''); setDigits(next); if (next[index] && index < 5) inputs.current[index + 1]?.focus(); };
  const handlePaste = (event: React.ClipboardEvent) => { event.preventDefault(); const pasted = event.clipboardData.getData('text').replace(/\D/g, '').slice(0, 6).split(''); setDigits(digits.map((_, index) => pasted[index] ?? '')); if (pasted.length) inputs.current[Math.min(pasted.length, 6) - 1]?.focus(); };
  const verify = async (event: React.FormEvent) => { event.preventDefault(); if (digits.join('').length !== 6) { setError('Enter the six-digit code to continue.'); return; } setLoading(true); setError(''); try { await onVerified(digits.join('')); } catch { setError('That code could not be verified. Please try again.'); setLoading(false); } };
  const resend = async () => { setResendLoading(true); setError(''); try { await onResend(); setSeconds(30); } catch { setError('We could not resend the code. Please try again.'); } finally { setResendLoading(false); } };
  return <div className="auth-content auth-animate"><button type="button" className="auth-back" onClick={onBack}><ArrowLeft size={16} /> Back</button><span className="auth-step">STEP 02 / VERIFY</span><h1>Verify your account.</h1><p className="auth-description">We&apos;ve sent a 6-digit verification code to<br /><strong>{identifier}</strong></p><form onSubmit={verify}><div className="otp-grid" onPaste={handlePaste}>{digits.map((digit, index) => <input key={index} ref={(element) => { inputs.current[index] = element; }} aria-label={`Verification digit ${index + 1}`} inputMode="numeric" maxLength={1} value={digit} onChange={(event) => updateDigit(index, event.target.value)} onKeyDown={(event) => { if (event.key === 'Backspace' && !digits[index] && index > 0) inputs.current[index - 1]?.focus(); }} />)}</div>{error ? <p className="auth-error auth-otp-error" role="alert">{error}</p> : null}<button className="auth-primary" type="submit" disabled={loading || resendLoading}>{loading ? <><span className="auth-spinner" /> Verifying...</> : 'Verify account'}</button></form><button className="auth-resend" type="button" disabled={seconds > 0 || resendLoading} onClick={resend}>{resendLoading ? <><span className="auth-spinner auth-spinner-small" /> Sending...</> : seconds > 0 ? `Resend OTP in 00:${String(seconds).padStart(2, '0')}` : <><RefreshCw size={15} /> Resend OTP</>}</button></div>;
}